### ISSUE TITLE
What flow to use for promptIfNotGranted to check if permission is given after dialog is shown

### ISSUE THREAD

**Issue by basvdijk** [inket/FullDiskAccess#1]
When I use this code:

```swift
FullDiskAccess.promptIfNotGranted(
    title: "Enable Full Disk Access for MacSymbolicator",
    message: "MacSymbolicator requires Full Disk Access to search for DSYMs using Spotlight.",
    settingsButtonTitle: "Open Settings",
    skipButtonTitle: "Later",
    canBeSuppressed: false, // `true` will display a "Do not ask again." checkbox and honor it
    icon: nil
)
```

I get the prompt and it works fine. However for me it is unclear how to go from here. As far as I can see there is no result given by `promptIfNotGranted` so I can detect what the user did and if permission is granted.

What approach do you suggest for this flow?

**Comment by inket** [comment]
There's no way for the app to be "notified" of the permission change, which means you have to query/poll each time with `FullDiskAccess.isGranted`.

The smart way to do this is to detect when your app becomes focused again, and check the permission there. (This is because the user needs to switch to the Settings app to change the permission then switch back to your app)

You may use `applicationDidBecomeActive(_ notification: [Notification])` for this

**Comment by basvdijk** [comment]
@inket Thanks for your swift reply! I'll look into that :)
